lint:coding-guideline:
  image: python:3-alpine
  before_script:
    - pip install pep8
  script:
    - pep8 .

test:
  image: python:3-alpine
  before_script:
    - apk add --no-cache gcc
    - pip install neovim
    - cd rplugin
  script:
    - python -m unittest test.test_neotags
